# Generated by Django 6.0.4 on 2026-04-21 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIWebhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("url", models.URLField()),
                (
                    "secret",
                    models.CharField(
                        blank=True,
                        help_text="Webhook secret for signature verification",
                        max_length=256,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("user_registered", "User Registered"),
                            ("purchase_completed", "Purchase Completed"),
                            ("investment_matured", "Investment Matured"),
                            ("api_key_created", "API Key Created"),
                            ("transaction_failed", "Transaction Failed"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        default=3, help_text="Number of retry attempts on failure"
                    ),
                ),
                ("timeout_seconds", models.IntegerField(default=10)),
                ("last_triggered", models.DateTimeField(blank=True, null=True)),
                ("last_response", models.JSONField(blank=True, null=True)),
                ("success_count", models.IntegerField(default=0)),
                ("failure_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name to identify this API key", max_length=100
                    ),
                ),
                ("key", models.CharField(editable=False, max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("revoked", "Revoked"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        default=dict, help_text="JSON object with permission scopes"
                    ),
                ),
                (
                    "allowed_ips",
                    models.JSONField(
                        default=list, help_text="List of allowed IP addresses"
                    ),
                ),
                ("rate_limit_per_minute", models.IntegerField(default=60)),
                ("rate_limit_per_hour", models.IntegerField(default=1000)),
                ("rate_limit_per_day", models.IntegerField(default=10000)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="APIRateLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint_pattern", models.CharField(default="*", max_length=200)),
                ("method", models.CharField(default="*", max_length=10)),
                ("limit_per_minute", models.IntegerField(default=60)),
                ("limit_per_hour", models.IntegerField(default=1000)),
                ("limit_per_day", models.IntegerField(default=10000)),
                ("current_usage", models.JSONField(default=dict)),
                ("last_reset", models.DateTimeField(auto_now=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.apikey",
                    ),
                ),
            ],
            options={
                "unique_together": {("api_key", "endpoint_pattern", "method")},
            },
        ),
        migrations.CreateModel(
            name="APIUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.CharField(max_length=500)),
                ("method", models.CharField(max_length=10)),
                ("status_code", models.IntegerField()),
                (
                    "response_time",
                    models.IntegerField(help_text="Response time in milliseconds"),
                ),
                (
                    "response_size",
                    models.IntegerField(
                        blank=True, help_text="Response size in bytes", null=True
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                (
                    "request_data",
                    models.TextField(
                        blank=True, help_text="JSON string of request data"
                    ),
                ),
                (
                    "response_data",
                    models.TextField(
                        blank=True, help_text="JSON string of response data"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.apikey",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="api_apiusag_timesta_137f2a_idx"
                    ),
                    models.Index(
                        fields=["api_key", "timestamp"],
                        name="api_apiusag_api_key_079fc6_idx",
                    ),
                    models.Index(
                        fields=["status_code"], name="api_apiusag_status__1beeb4_idx"
                    ),
                ],
            },
        ),
    ]
